name: Build MCVR

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout MCVR
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          # Используем vcpkg для быстрой установки Vulkan
          vcpkg install vulkan:x64-windows
          # Указываем путь к vcpkg, чтобы CMake его нашел
          echo "VULKAN_SDK=$env:VCPKG_INSTALLATION_ROOT/installed/x64-windows" >> $env:GITHUB_ENV

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Configure CMake
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 `
          -DJAVA_PROJECT_ROOT_DIR="$env:GITHUB_WORKSPACE" `
          -DMCVR_ENABLE_NRD=ON -DUSE_AMD=ON `
          -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"

      - name: Build Release
        run: cmake --build build -j --config Release

      - name: Install (Prepare Artifacts)
        run: cmake --install build --config Release --prefix ./dist

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: MCVR-Build-Windows
          path: ./dist
