name: Build MCVR

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout MCVR
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: |
          # Используем системный vcpkg, который уже есть на Windows-2022
          # Он содержит Vulkan и другие нужные библиотеки
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 `
          -DJAVA_PROJECT_ROOT_DIR="$env:GITHUB_WORKSPACE" `
          -DMCVR_ENABLE_NRD=ON -DUSE_AMD=ON `
          -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"

      - name: Build Release
        run: cmake --build build -j --config Release

      - name: Install
        run: cmake --install build --config Release --prefix ./dist

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MCVR-Build
          path: ./dist
